name: search_autocomplete
description: A Flutter autocomplete search widget with custom dropdowns and Cubit/BLoC support.
version: 0.0.8
homepage: https://github.com/Okladnoj/search_autocomplete
repository: https://github.com/Okladnoj/search_autocomplete

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:


keywords:
  - flutter
  - autocomplete
  - search
  - dropdown
  - cubit
  - bloc
  - state management
  - ui
  - form
  - text field

license: MIT
