name: search_autocomplete
description: A Flutter autocomplete search widget with custom dropdowns and Cubit/BLoC support.
version: 1.0.0
homepage: https://github.com/Okladnoj/search_autocomplete
repository: https://github.com/Okladnoj/search_autocomplete
issue_tracker: https://github.com/Okladnoj/search_autocomplete/issues

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

keywords:
  - flutter
  - autocomplete
  - search
  - dropdown
  - cubit
  - bloc
  - state management
  - ui
  - form
  - text field

topics:
  - search
  - drop-down
  - search-field
  - autocomplete

license: MIT
