abstract class Constants {
  static const collocations = [
    'A bird in the hand is worth two in the bush',
    'A penny for your thoughts',
    'Actions speak louder than words',
    'Add insult to injury',
    'Bite the bullet',
    'Break the ice',
    'Burning the midnight oil',
    'Call it a day',
    'Catch-22',
    'Chip on your shoulder',
    'Cry over spilt milk',
    'Cutting corners',
    'Don\'t cry over spilled milk',
    'Don\'t give up the day job',
    'Every cloud has a silver lining',
    'Fit as a fiddle',
    'Get out of hand',
    'Give someone the cold shoulder',
    'Go back to the drawing board',
    'Go the extra mile',
    'Hit the nail on the head',
    'Ignorance is bliss',
    'It\'s not rocket science',
    'Jump on the bandwagon',
    'Keep something at bay',
    'Kill two birds with one stone',
    'Last straw',
    'Let the cat out of the bag',
    'Miss the boat',
    'No pain, no gain',
    'Once in a blue moon',
    'Piece of cake',
    'Put the cart before the horse',
    'Rain on someone\'s parade',
    'Saving for a rainy day',
    'See eye to eye',
    'Sit on the fence',
    'Speak of the devil',
    'Steal someone\'s thunder',
    'Take with a grain of salt',
    'The ball is in your court',
    'The best of both worlds',
    'The devil is in the details',
    'The early bird gets the worm',
    'The elephant in the room',
    'Throw in the towel',
    'To get bent out of shape',
    'To make matters worse',
    'Under the weather',
    'We\'ll cross that bridge when we come to it',
    'You can\'t judge a book by its cover',
    'Bite the dust',
    'Break a leg',
    'Close, but no cigar',
    'Cry wolf',
    'Don\'t count your chickens before they hatch',
    'Fish out of water',
    'Get your act together',
    'Hang in there',
    'Hit the sack',
    'It\'s a piece of cake',
    'Jump to conclusions',
    'Keep your chin up',
    'Let sleeping dogs lie',
    'No use crying over spilled milk',
    'Off the hook',
    'Pull yourself together',
    'Read between the lines',
    'See the light at the end of the tunnel',
    'Take it with a grain of salt',
    'The bigger they are, the harder they fall',
    'Throw caution to the wind',
    'An arm and a leg',
    'Break the bank',
    'Cut to the chase',
    'Down and out',
    'Get over it',
    'Honesty is the best policy',
    'It takes one to know one',
    'Keep an eye on him',
    'Let bygones be bygones',
    'Needle in a haystack',
    'On the ball',
    'Put a sock in it',
    'Rome wasn\'t built in a day',
    'Stab someone in the back',
    'The best thing since sliced bread',
    'The whole nine yards',
    'Up in arms',
    'You can say that again',
    'At the drop of a hat',
    'Bite off more than you can chew',
    'Comparing apples to oranges',
    'Don\'t bite the hand that feeds you',
    'From rags to riches',
    'Hit the books',
    'In the nick of time',
    'Kill time',
    'Let your hair down',
    'Never say never',
    'On cloud nine',
    'Put your foot in your mouth',
    'Run out of steam',
    'The ball is in your court',
    'The sky is the limit',
    'When pigs fly',
    'Your guess is as good as mine',
    'Back to square one',
    'Come hell or high water'
  ];
}
